'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {careers,searchCareers} from '../lib/careers';

export default function Home(){
  const [query,setQuery]=useState(''),[market,setMarket]=useState(null);
  useEffect(()=>{fetch('/api/market?summarize=1').then(response=>response.json()).then(setMarket).catch(()=>{})},[]);
  const results=query.trim()?searchCareers(query):careers.slice(0,8);
  return <><nav><Link className="logo" href="/">NEX<span>ORA</span></Link><div className="links"><Link href="/careers">Careers</Link><Link href="/trending">Trending</Link><Link href="/journey">My Journey</Link><Link href="/proofwork">ProofWork</Link></div><Link className="user" href="/journey">◉</Link></nav><main><section className="hero"><div className="grid"/><div className="heroIn"><small>CAREER INTELLIGENCE · PROOFWORK</small><h1>KNOW THE <i>PATH.</i><br/>PROVE THE <i>SKILL.</i></h1><p>Discover where you want to go, learn what the role actually demands, and prove what you can do.</p><Link className="primary" href="#careers">EXPLORE CAREERS</Link><Link className="proofLink" href="/proofwork">Open ProofWork ↗</Link></div></section><section id="careers" className="section"><header><div><small>CAREER MAP</small><h2>Choose your <i>destination.</i></h2></div><p>Search by role, skill, category, or the kind of work you want to do.</p></header><div className="careerSearch"><span>⌕</span><input aria-label="Search careers" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search music, Python, design, data..."/></div><div className="cards">{results.map(career=><Link className="card" key={career.slug} href={`/careers/${career.slug}`}><b className="icon">✦</b><h3>{career.title}</h3><p>{career.description}</p><div>{career.skills.slice(0,3).map(skill=><span key={skill}>{skill}</span>)}</div><strong>Explore →</strong></Link>)}</div></section><section className="market"><div><small>AI MARKET PULSE</small><h2>Roles worth <i>watching.</i></h2><p>{market?.summary||market?.notice||'Reading current demand signals...'}</p><Link className="textLink" href="/trending">See the full market map →</Link></div><div className="trendList">{(market?.jobs||[]).map(job=><div className="trendItem" key={job.role}><b>{job.role}</b><span>{job.demandIndicator} · {job.geography}</span></div>)}</div></section><section className="aboutBand"><small>ABOUT NEXORA</small><h2>Created by <i>ABHI RAI.</i></h2><p>Career intelligence · learning paths · skill proof · market signals</p></section></main><footer><b>NEX<span>ORA</span></b><span>Know the path. Prove the skill.</span></footer></>;
}