'use client';
import {useEffect,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {getCareer} from '../../../lib/careers';

export default function LearningClient({slug}) {
  const career=getCareer(slug),router=useRouter(),search=useSearchParams();
  const [topic,setTopic]=useState(search.get('topic')||career?.skills[0]||'the fundamentals');
  const [language,setLanguage]=useState('English'),[data,setData]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const [completedCount,setCompletedCount]=useState(0),[celebrate,setCelebrate]=useState(false),[nextTopic,setNextTopic]=useState('');
  useEffect(()=>{const next=search.get('topic');if(next)setTopic(next)},[search]);
  useEffect(()=>{if(!career)return;const topicList=[...new Set(career.skills.concat(career.tools))],completed=JSON.parse(localStorage.getItem('nexora-completed-topics')||'[]'),finished=topicList.filter(item=>completed.includes(`${career.slug}:${item}`));setCompletedCount(Math.round(finished.length/topicList.length*100));if(completed.includes(`${career.slug}:${topic}`))setData(current=>({...current,completed:true}))},[career,topic]);
  useEffect(()=>{if(!career||!topic)return;setLoading(true);setError('');fetch(`/api/learning?career=${encodeURIComponent(career.title)}&topic=${encodeURIComponent(topic)}&language=${encodeURIComponent(language)}`).then(response=>response.json().then(body=>{if(!response.ok)throw new Error(body.error);return body})).then(setData).catch(reason=>setError(reason.message)).finally(()=>setLoading(false))},[career,topic,language]);
  if(!career)return <main className="workspace"><p>Learning topic not found.</p></main>;
  const topics=[...new Set(career.skills.concat(career.tools))];
  function markDone(){const key=`${career.slug}:${topic}`;const completed=JSON.parse(localStorage.getItem('nexora-completed-topics')||'[]');if(!completed.includes(key))completed.push(key);localStorage.setItem('nexora-completed-topics',JSON.stringify(completed));const finished=completed.filter(item=>item.startsWith(`${career.slug}:`));setCompletedCount(Math.round(finished.length/topics.length*100));setNextTopic(topics.find(item=>!completed.includes(`${career.slug}:${item}`))||'');setCelebrate(true);setData({...data,completed:true});window.setTimeout(()=>setCelebrate(false),3200)}
  const testLink=data?.completed?<Link className="primary" href={`/test?career=${career.slug}&topic=${encodeURIComponent(topic)}`}>TEST THIS SKILL</Link>:<span className="lockedTest">Mark this topic complete to unlock its skill test.</span>;
  const nextLink=nextTopic&&data?.completed?<Link className="secondary" href={`/learn/${career.slug}?topic=${encodeURIComponent(nextTopic)}`}>CONTINUE TO {nextTopic.toUpperCase()} →</Link>:null;
  return <><nav><Link className="logo" href="/">NEX<span>ORA</span></Link><div className="links"><Link href="/careers">Careers</Link><Link href="/journey">My Journey</Link><Link href="/proofwork">ProofWork</Link></div></nav><main className="workspace learningPage"><button className="back backButton" onClick={()=>router.back()}>← Back</button><small>LEARNING STUDIO · {career.title}</small><h1>Start reading <i>{topic}.</i></h1><p className="lead left">Begin with the reading and resources below. Complete this topic, test it, then continue to the next one.</p><div className="topicBubbles">{topics.map((item,index)=><button className={`topicBubble ${item===topic?'active':''}`} style={{'--bubble':`${(index*47)%360}deg`}} onClick={()=>setTopic(item)} key={item}>{item}</button>)}</div><div className="languageBar"><label>Playlist language<select value={language} onChange={event=>setLanguage(event.target.value)}><option>English</option><option>Hindi</option><option>Spanish</option><option>French</option></select></label><span>{loading?'Refreshing learning route...':data?.notice||'Reading resources are ready.'}</span></div>{error&&<div className="aiError" role="alert">{error}</div>}<div className="learningColumns"><section className="learningCopy"><small>UNDERSTAND</small><h2>Build the working <i>mental model.</i></h2><p>{topic} matters because it helps a {career.title} make better decisions.</p><h3>Recommended concepts</h3>{career.skills.map(skill=><p className="check" key={skill}>✓ {skill}</p>)}<h3>Practice brief</h3><p>Make one small example using {topic}. Record the problem, approach, result, and next improvement.</p><button className="secondary" onClick={markDone}>{data?.completed?'TOPIC COMPLETE':'MARK TOPIC AS DONE'}</button> {testLink} {nextLink}{celebrate&&<div className="completionToast" role="status"><strong>Congratulations.</strong><span>{topic} complete. Progress {completedCount}%</span><b><i style={{width:`${completedCount}%`}}/></b></div>}</section><aside className="resourceRail"><small>RESOURCES FOR {topic.toUpperCase()}</small>{data?.resources?.map(resource=><a className="resourceBubble" href={resource.url} target="_blank" rel="noreferrer" key={resource.url}><b>{resource.title}</b><span>{resource.source} · {resource.type}</span><strong>Open resource ↗</strong></a>)}<small className="playlistLabel">FROM BEGINNING TO MASTERY</small>{data?.playlists?.length?data.playlists.map(playlist=><a className="playlistBubble" href={playlist.url} target="_blank" rel="noreferrer" key={playlist.url}><b>{playlist.title}</b><span>{playlist.source} · {playlist.language}</span><strong>Play playlist ↗</strong></a>):<div className="emptyResource"><p>{data?.notice||'Playlist discovery is loading.'}</p><span>Configure YOUTUBE_API_KEY for live playlist results.</span></div>}</aside></div></main><footer><b>NEX<span>ORA</span></b><span>Learn with a path, not a pile of links.</span></footer></>;
}
