import {NextResponse} from 'next/server';
import {generateAIResponse,parseAIJson} from '../../../lib/ai/provider';

const sourceUrl='https://remotive.com/api/remote-jobs?limit=100';
const categoryFor=title=>{const value=title.toLowerCase();if(/design|ux|ui|visual/.test(value))return 'Design';if(/market|sales|business|finance|account|product|customer/.test(value))return 'Business';if(/music|audio|sound|video|content|writer|game/.test(value))return 'Creative';return 'Technology'};
const indicatorFor=count=>count>=8?'High':count>=4?'Rising':count>=2?'Growing':'Emerging';
function weeklyPulse(jobs){const now=Date.now(),weeks=[0,1,2,3,4].map(week=>jobs.filter(job=>now-new Date(job.publication_date||job.created_at||now).getTime()>=week*604800000&&now-new Date(job.publication_date||job.created_at||now).getTime()<(week+1)*604800000).length);const peak=Math.max(...weeks,1);return weeks.reverse().map(value=>Math.round(value/peak*100))}
async function fetchOnlineJobs(){const response=await fetch(sourceUrl,{headers:{Accept:'application/json'},next:{revalidate:1800}});if(!response.ok)throw new Error(`Market provider returned ${response.status}.`);const data=await response.json();return Array.isArray(data.jobs)?data.jobs:[]}
export async function GET(req){try{const onlineJobs=await fetchOnlineJobs();const grouped=new Map();for(const job of onlineJobs){const role=(job.title||'').replace(/\s+/g,' ').trim();if(!role)continue;const key=role.toLowerCase();const current=grouped.get(key)||{role,category:categoryFor(role),postings:[]};current.postings.push(job);grouped.set(key,current)}const jobs=[...grouped.values()].sort((a,b)=>b.postings.length-a.postings.length).slice(0,15).map(item=>({role:item.role,category:item.category,demandIndicator:indicatorFor(item.postings.length),geography:'Remote',postings:item.postings.length,pulse:weeklyPulse(item.postings),periods:['4 weeks ago','3 weeks ago','2 weeks ago','Last week','This week'],url:item.postings[0]?.url||null}));const data={source:'Remotive live job listings',lastUpdated:new Date().toISOString(),isLive:true,notice:'Demand signals are calculated from current online job listings and grouped by role title.',categories:[...new Set(jobs.map(job=>job.category))],jobs};if(new URL(req.url).searchParams.get('summarize')!=='1')return NextResponse.json(data);const response=await generateAIResponse({messages:[{role:'system',content:'Summarize this live job-listing snapshot without inventing statistics. Return JSON: {"summary":"string"}.'},{role:'user',content:JSON.stringify(jobs)}],temperature:.2});return NextResponse.json({...data,summary:parseAIJson(response)?.summary||'Live job listings are available below.',mode:response.mode||'live'})}catch(error){console.error('[NEXORA market]',error);return NextResponse.json({source:'Unavailable',lastUpdated:null,isLive:false,notice:'Live market data is temporarily unavailable. No synthetic demand data is being shown.',categories:[],jobs:[]},{status:200})}}
