'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';

export default function TopicTestClient(){
  const search=useSearchParams(),career=search.get('career')||'',topic=search.get('topic')||'this topic';
  const [questions,setQuestions]=useState([]),[answers,setAnswers]=useState({}),[status,setStatus]=useState('loading'),[result,setResult]=useState(null),[error,setError]=useState('');
  useEffect(()=>{fetch('/api/assessment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({career,topic,seed:Date.now()})}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setQuestions(body.questions);setStatus('ready')}).catch(reason=>{setError(reason.message);setStatus('error')})},[career,topic]);
  async function submit(){setStatus('grading');const response=await fetch('/api/assessment/grade',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target:career,topic,questions,answers})});const body=await response.json();if(!response.ok){setError(body.error);setStatus('error');return}setResult(body);setStatus('complete')}
  return <><nav><Link className="logo" href="/">NEX<span>ORA</span></Link><div className="links"><Link href="/careers">Careers</Link><Link href="/trending">Trending</Link><Link href="/journey">My Journey</Link><Link href="/proofwork">ProofWork</Link></div></nav><main className="workspace topicTest"><Link className="back" href={`/learn/${career}?topic=${encodeURIComponent(topic)}`}>← Back to learning</Link><small>SKILL CHECK · {topic.toUpperCase()}</small><h1>Test your <i>understanding.</i></h1><p className="lead left">Fresh questions about {topic}, so completing a lesson leads to a meaningful check of the skill.</p>{error&&<div className="aiError">{error}</div>}{status==='loading'&&<p>Building your topic questions...</p>}{status==='ready'&&<section className="testQuestions">{questions.map((question,index)=><article key={question.id||index}><small>{question.difficulty} · {question.skill||topic}</small><h2>{index+1}. {question.question}</h2><textarea value={answers[question.id]||''} onChange={event=>setAnswers({...answers,[question.id]:event.target.value})} placeholder="Write your answer..." rows="5"/></article>)}<button className="primary" onClick={submit}>SUBMIT SKILL CHECK</button></section>}{status==='grading'&&<p>Reviewing your answers...</p>}{status==='complete'&&<section className="testResult"><small>SKILL CHECK COMPLETE</small><h2>{result.score}/100</h2><p>{result.summary}</p><p>Understanding: {result.understanding} · Practical ability: {result.practicalAbility}</p><Link className="primary" href={`/learn/${career}?topic=${encodeURIComponent(topic)}`}>RETURN TO LEARNING</Link></section>}</main></>;
}
