'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {careers,searchCareers} from '../../lib/careers';

export default function Journey(){
  const [goal,setGoal]=useState(''),[query,setQuery]=useState(''),[history,setHistory]=useState([]),[done,setDone]=useState([]);
  useEffect(()=>{try{setHistory(JSON.parse(localStorage.getItem('nexora-history')||'[]'));const linked=new URLSearchParams(window.location.search).get('career');setGoal(linked||localStorage.getItem('nexora-goal')||'');setDone(JSON.parse(localStorage.getItem('nexora-completed-topics')||'[]'))}catch{}},[]);
  function chooseCareer(slug){setGoal(slug);localStorage.setItem('nexora-goal',slug)}
  const career=careers.find(item=>item.slug===goal),options=query.trim()?searchCareers(query):careers;
  const topics=career?[...new Set(career.skills.concat(career.tools))]:[],completed=topics.filter(topic=>done.includes(`${career?.slug}:${topic}`)),progress=topics.length?Math.round(completed.length/topics.length*100):0;
  return <><nav><Link className="logo" href="/">NEX<span>ORA</span></Link><div className="links"><Link href="/careers">Careers</Link><Link href="/trending">Trending</Link><Link href="/journey">My Journey</Link><Link href="/proofwork">ProofWork</Link></div></nav><main className="workspace"><small>MY JOURNEY</small><h1>Make the next step <i>visible.</i></h1>{!career?<div className="goalPicker"><p className="lead left">Search for the career you want to build toward.</p><input className="goalSearch" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Try music, Python, creative, or data" aria-label="Search career goals"/><div className="goalResults">{options.map(item=><button className={item.slug===goal?'selectedCareer':''} onClick={()=>chooseCareer(item.slug)} key={item.slug}><span>{item.title}<small>{item.category}</small></span><b>Choose →</b></button>)}{!options.length&&<p>No careers found. Try a broader search.</p>}</div></div>:<><section className="journeyHeader"><div><small>CURRENT GOAL</small><h2>{career.title}</h2><p>{career.description}</p><Link className="textLink" href="/journey">Change career</Link></div><strong>{progress}%<small>PROGRESS</small></strong></section><div className="journeyStages">{career.stages.map((stage,index)=><article key={stage.stage}><small>0{index+1} · {stage.stage}</small><h2>{stage.stage}</h2>{stage.topics.map(item=>{const complete=done.includes(`${career.slug}:${item}`);return <div className="journeyTopic" key={item}><span>{complete?'✓':'○'} {item}</span><Link href={complete?`/test?career=${career.slug}&topic=${encodeURIComponent(item)}`:`/learn/${career.slug}?topic=${encodeURIComponent(item)}`}>{complete?'Test skill':'Learn'}</Link></div>})}</article>)}</div><section className="scoreboard"><div><small>SCOREBOARD</small><h2>{history.length} assessments completed</h2><p>Learning builds the evidence. Topic tests show whether it stayed with you. ProofWork is separate resume preparation for interviews and companies.</p></div><Link className="proofLink" href="/proofwork">Open ProofWork ↗</Link></section></>}</main><footer><div><b>NEX<span>ORA</span></b><p>Know the path. Prove the skill.</p></div><div><small>ABOUT NEXORA</small><p>Created by ABHI RAI</p><p>Career intelligence · learning paths · skill proof · market signals</p></div></footer></>;
}